fix: not use user-controlled data directly in a run block

diff --git a/.github/actions/build/action.yml b/.github/actions/build/action.yml
--- a/.github/actions/build/action.yml
+++ b/.github/actions/build/action.yml
@@ -17,13 +17,14 @@ runs:
   steps:
     - name: Move to the working directory
       shell: bash
-      run: cd "${{ inputs.workspace }}"
-
+      run: |
+        cd "$WORKSPACE" || { echo "Workspace not found"; exit 1; }
+      env:
+        WORKSPACE: ${{ inputs.workspace }}
     - name: Run build
       shell: bash
       run: |
         ${{ inputs.command-to-build }} ${{ inputs.output-dir }}
-
     - name: Upload build artifact
       uses: actions/upload-artifact@v4
       with:
diff --git a/.github/actions/publish-codecov-report/action.yml b/.github/actions/publish-codecov-report/action.yml
--- a/.github/actions/publish-codecov-report/action.yml
+++ b/.github/actions/publish-codecov-report/action.yml
@@ -15,14 +15,19 @@ runs:
   steps:
     - name: Move to the working directory
       shell: bash
-      run: cd "${{ inputs.workspace }}"
+      run: |
+        cd "$WORKSPACE" || { echo "Workspace not found"; exit 1; }
+      env:
+        WORKSPACE: ${{ inputs.workspace }}
+        
     - name: Output a Coverage report
       shell: bash
       run: pnpm test:coverage --runInBand
+
     - name: Upload results to Codecov
       uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
       with:
-        token: "${{ inputs.token }}"
-        files: "coverage/${{ inputs.files }}"
+        token: ${{ inputs.token }}
+        files: ${{ format('coverage/{0}', inputs.files) }}
         disable_search: true
         fail_ci_if_error: true
diff --git a/.github/actions/setup-and-run-cypress/action.yml b/.github/actions/setup-and-run-cypress/action.yml
--- a/.github/actions/setup-and-run-cypress/action.yml
+++ b/.github/actions/setup-and-run-cypress/action.yml
@@ -12,12 +12,17 @@ runs:
   steps:
     - name: Move to the working directory
       shell: bash
-      run: cd "${{ inputs.workspace }}"
+      run: |
+        cd "$WORKSPACE" || { echo "Workspace not found"; exit 1; }
+      env:
+        WORKSPACE: ${{ inputs.workspace }}
+        
     - name: Ensure Cypress binary is installed
       shell: bash
-      run: pnpm cypress install
+      run: pnpm exec cypress install
+
     - name: Run Functional tests
       shell: bash
       env:
         CYPRESS_BASE_URL: ${{ inputs.url }}
-      run: pnpm cypress run --browser chrome
+      run: pnpm exec cypress run --browser chrome
